apiVersion: apps/v1
kind: Deployment
metadata:
  name: kict-aichatbot-frontend
  namespace: aicarechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kict-aichatbot-frontend
  template:
    metadata:
      labels:
        app: kict-aichatbot-frontend
    spec:
      containers:
        - name: kict-aichatbot-frontend
          image: registry.gitlab.com/jmk4560/kict_aichatbot_frontend:latest  # 최신 이미지를 사용
          ports:
            - containerPort: 5001
      imagePullSecrets:
        - name: regcred  # 프라이빗 레지스트리의 경우 필요