apiVersion: v1
kind: Service
metadata:
  name: kict-aichatbot-service
  namespace: aicarechat
spec:
  type: NodePort  # 외부에서 접근 가능하게 설정
  selector:
    app: kict-aichatbot-frontend
  ports:
    - port: 5001           # 서비스 포트
      targetPort: 5001      # 파드 내부 포트
      nodePort: 30001       # 외부에서 접근 가능한 포트 (30000-32767 사이)
